appName: "Loader Node"
mode: SINGLE_NODE
serverConfigFile: "./loader-node/config/loader-server.json"
agentConfigFile: "./loader-node/config/loader-agent.json"

server:
  applicationConnectors:
    - type: http
      port: 9999
  adminConnectors:
    - type: http
      port: 9991

logging:
  level: INFO
